// app/layout.js
import Navbar from "@/app/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <link href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" rel="stylesheet" />
        <script src="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.js" defer></script>
      </head> */}
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
